name: Java CI with Gradle And Docker
on:
  push:
    branches: dev
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with test
      - name: Build with Gradle
        run: ./gradlew clean build

      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 도커 이미지 빌드 및 도커 허브에 push
      # docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker image build and push
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/back .
          docker push ${{ secrets.DOCKER_REPO }}/back
